Golf4/Golf4/Controllers/HomeCompController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using Golf4.Models;
using Npgsql;

namespace Golf4.Controllers
{
    public class HomeCompController : Controller
    {
        [AllowAnonymous]
        // GET: HomeComp
        public ActionResult Index()
        {
            HomeCompModels.Contest contests = new HomeCompModels.Contest();
            HomeCompModels Model = new HomeCompModels();
            Model.AllContests = contests.GetAllContests();
            Model.CompetitionInfo = contests.Info4Competition(Model.ContestID);

            return View(Model);
        }
        [AllowAnonymous]
        [HttpGet]
        public ActionResult CompetitionInfo()
        {
            HomeCompModels.Contest contests = new HomeCompModels.Contest();
            HomeCompModels hcm = new HomeCompModels();
            hcm.CompetitionInfo = contests.Info4Competition(Convert.ToInt16(Request.QueryString["cont"]));
            return View(hcm);
        }

    }

}

Golf4/Golf4/Views/HomeComp/CompetitionInfo.cshtml
@model Golf4.Models.HomeCompModels
@using Golf4.Controllers;
@using System.Data

<h3>Vald tävling</h3>

<hr />

<div class="displayComp">
<table id="CompeteInfo">
    <tr>
        <td id="compName">@Html.DisplayFor(model => model.Name)</td>
    </tr>
    <tr>
        <td>Tillfälle: <b>@Html.DisplayFor(model => model.Timestart)</b></td>
    </tr>
    <tr>
        <td>Sista anmälningsdag: <b>@Html.DisplayFor(model => model.CloseTime)</b></td>
    </tr>
    <tr>
        <td>Beskrivning: <br />@Html.DisplayFor(model => model.description)</td>
    </tr>
</table>
</div>

Golf4/Golf4/Views/HomeComp/CompetitionList.cshtml
@model Golf4.Models.HomeCompModels
@using Golf4.Controllers;
@using System.Data

<h3>Inplanerade tävlingar</h3>
<hr />
<div class="contestList">

    <script type="text/javascript" src="https://cdn.datatables.net/v/dt/jq-2.2.4/dt-1.10.13/datatables.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular-animate.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.10.13/datatables.min.css" />

    @*<div id="imgloader" style="display:none;position:absolute;top:50%;left:50%;padding:2px;">
        <img src="~/Content/img/bx_loader.gif" />
    </div>*@    

    angular.module('app', ['ngAnimate']);

        <table id="contests">
            <thead>
                <tr>
                    @foreach (DataColumn column in Model.AllContests.Columns)
                    {
                        <th> @column.ColumnName</th>
                    }

                </tr>
            </thead>

            <tbody>
                @foreach (DataRow row in Model.AllContests.Rows)
            {
                    <tr>
                        @foreach (DataColumn item in Model.AllContests.Columns)
                        {
                            <td>
                                @if (item.ColumnName == "id")
                                {
                                    @*@Ajax.ActionLink("Mer info", "Index", "homeComp", new AjaxOptions{
                                        UpdateTargetId = "CompeteInfo",
                                        OnBegin = "fnOnBegin",
                                        InsertionMode = InsertionMode.Replace,
                                        HttpMethod = "GET",
                                        LoadingElementId = "imgloader",
                                        OnSuccess = "ifSuccessful"*@
                                    <input type="button" value="Mer Info" ng-click="ShowHide()" />
                                }
                                else
                                {
                                    @row[item.ColumnName];
                                }
                            </td>
                        }

                    </tr>
                }
        </table>
        <script>
            $(document).ready(function () {
                $('#contests').DataTable({
                    select: true
                })
            }
                );
            function ifSuccessful() {
                alert("Läs om tävlingen nedan");
            }
        </script>
</div>

Golf4/Golf4/Views/HomeComp/Index.cshtml
@model Golf4.Models.HomeCompModels
@using Golf4.Controllers;
@using System.Data

@{
    ViewBag.Title = "Index";
}

<script type="text/javascript" src="https://cdn.datatables.net/v/dt/jq-2.2.4/dt-1.10.13/datatables.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular-animate.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.10.13/datatables.min.css" />

<h2> Tävlingar</h2>
<hr />
<h5> Varje säsong har Hålslagets Golfklubb en mängd olika tävlingar;
    t.ex. två nationella tourer har valt att hålla en av sina tävlingar hos oss under 2017 och vi har även det årliga Klubbmästerskapet. 
    På den här sidan kommer du få uppdaterat information om vilka tävlingar som är inplanerade för tillfället. 
    Titta in då och då så du inte missar någon av våra tävlingar. 
    Ett fantastiskt tillfälle att komma ut på banan och träffa nya trevliga människor under spelet av den sport vi alla älskar!</h5>
<br />

<h3>Regler</h3>
<h5>I dagens läge så utförs alla våra tävlingar genom slagspel av typen <i>poängbogey</i>. Kan du inte reglerna så finns den ett regelhäfte att hämta i receptionen.</h5>
<br />

<script type="text/javascript">
        //var app = angular.module('MyApp', ['ngAnimate'])
        //app.controller('MyController', function ($scope) {
        //    //This will hide the DIV by default.
        //    $scope.IsVisible = false;
        //    $scope.ShowHide = function () {
        //        //If DIV is visible it will be hidden and vice versa.
        //        $scope.IsVisible = $scope.IsVisible ? false : true;
        //    }
        //})
        //$(document).ready(function () {
        //        $('#contests').DataTable({
        //            select: true
        //        })
        //    }
        //        );
        //    //function ifSuccessful() {
        //    //    alert("Läs om tävlingen nedan");
        //    //};
</script>

@*@Html.Partial("CompetitionList")*@
<div class="CompetitionList">
    <table id="contests">
        <thead>
            <tr>
                @foreach (DataColumn column in Model.AllContests.Columns)
            {
                    <th> @column.ColumnName</th>
                }

            </tr>
        </thead>

        <tbody>
            @foreach (DataRow row in Model.AllContests.Rows)
            {
                <tr>
                    @foreach (DataColumn item in Model.AllContests.Columns)
                {
                        <td>
                            @if (item.ColumnName == "id")
                            {
                                @Html.ActionLink("Mer info", "CompetitionInfo", "HomeComp", new { cont = row[item.ColumnName] }, null)
                                @*@Ajax.ActionLink("Mer info", "Index", "homeComp", new AjaxOptions{
                                    UpdateTargetId = "CompeteInfo",
                                    OnBegin = "fnOnBegin",
                                    InsertionMode = InsertionMode.Replace,
                                    HttpMethod = "GET",
                                    LoadingElementId = "imgloader",
                                    OnSuccess = "ifSuccessful"*@
                                @*<input type="button" value="Mer Info" ng-click="ShowHide()" />*@
                            }
                            else
                            {
                                @row[item.ColumnName];
                            }
                        </td>
                    }

                </tr>
            }
    </table>
</div>

<script>
    $(document).ready(function () {
        $('#contests').DataTable({
            language: {
                url: '//cdn.datatables.net/plug-ins/1.10.12/i18n/Swedish.json'
            },
        })
    }
    );
</script>

@*<div ng-show="IsVisible">
    <table id="CompeteInfo">
        <tr>
            <td>@Html.DisplayFor(model => model.Name)</td>
        </tr>
        <tr>
            <td>@Html.DisplayFor(model => model.ContestID)</td>
        </tr>
        <tr>
            <td>@Html.DisplayFor(model => model.Timestart)</td>
        </tr>
        <tr>
            <td>@Html.DisplayFor(model => model.CloseTime)</td>
        </tr>
        <tr>
            <td>@Html.DisplayFor(model => model.description)</td>
        </tr>
    </table>
</div>*@
    @*<div id="CompeteInfo">
        @Html.Partial("CompetitionInfo")
    </div>*@

    <hr />
    <br />
    <h5> Har du några frågor om någon av våra tävlingar eller behöver du hjälp att anmäla dig? Kontakta då receptionen på <b>info@hgk.se</b></h5>
<h5>Här kan ni hämta hem vårat tomma scorekort.</h5>
<p>
    <a class="btn btn-default" href="~/Scorecard/ScorecardEmpty"> Scorekort &raquo;</a>
</p>