Golf4/Golf4/Models/Member.cs
using Npgsql;
using System.Collections.Generic;

namespace Golf4.Models
{
    public class Member
    {
        public int ID { get; set; } = 0;
        public string Firstname { get; set; } = "";
        public string Lastname { get; set; } = "";
        public string Adress { get; set; } = "";
        public string Postalcode { get; set; } = "";
        public string City { get; set; } = "";
        public string Email { get; set; } = "";
        public Gender Gender { get; set; }
        public double HCP { get; set; } = 0.0;
        public int GolfID { get; set; } = 0;
        public Membercategory Membercategory { get; set; } = new Membercategory();
        public string Telefone { get; set; } = "";

        public static void Reservation(Reservation reservation)
        {
            PostgresModels Database = new PostgresModels();
            Database.SqlNonQuery("INSERT INTO reservation(timestart, timeend, closed, user) VALUES(@timestart, @timeend, @closed, @user)", PostgresModels.list = new List<NpgsqlParameter>()
            {                
                 new NpgsqlParameter("@timestart", reservation.Timestart),
                 new NpgsqlParameter("@timeend", reservation.Timeend),
                 new NpgsqlParameter("@closed", reservation.Closed),
                 new NpgsqlParameter("@user", reservation.ID)
            });           
        }

        public static void Reservation(List<int> memberid, int reservationid)
        {
            PostgresModels Database = new PostgresModels();
            foreach (int userid in memberid)
            {
                Database.SqlNonQuery("INSERT INTO balls(userid, reservationid) VALUES(@userid, @reservationid)", PostgresModels.list = new List<NpgsqlParameter>()
                {
                     new NpgsqlParameter("@userid", userid),
                     new NpgsqlParameter("@reservationid", reservationid)
                });
            }
        }

        public static void RemoveReservation(int reservationid)
        {
            PostgresModels Database = new PostgresModels();
            Database.SqlNonQuery("DELETE FROM reservation WHERE id = @reservationid", PostgresModels.list = new List<NpgsqlParameter>()
            {
                new NpgsqlParameter("@reservationid", reservationid),
            });
        }
    }

    public enum Gender
    {
        Male = 1,
        Female = 2,
    }
}

Golf4/Golf4/Controllers/ContestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using Golf4.Models;
using Npgsql;

namespace Golf4.Controllers
{
    public class ContestController : Controller
    {
        //GET: Contests
        [AllowAnonymous]
        public ActionResult Contests()
        {
            ContestModels.Contest contests = new ContestModels.Contest();
            ContestModels model = new ContestModels();
            model.AllContests = contests.GetAllContestsGuests();

            return View(model);
        }

        // GET: Contest
        public ActionResult Index()
        {
            ContestModels.Contest contests = new ContestModels.Contest();
            ContestModels model = new ContestModels();
            model.AllContests = contests.GetAllContests();

            model.PublishedContests = contests.GetPublishedContests();

            return View(model);
        }
        public ActionResult create()
        {
            return View();
        }
        [HttpPost]
        [Authorize(Roles = "2")]
        public ActionResult create(ContestModels model)
        {
            if (!ModelState.IsValid)
            {
                // om inte rätt format
                return View(model);
            }
            ReservationModels.CancelReservationsWhenContest(model.Timestart, model.Timeend, 1);
            ContestModels.MakeCompetition create = new ContestModels.MakeCompetition();
            create.Createcontest(Convert.ToInt32(User.Identity.Name) , model.Name, model.Timestart, model.Timeend, model.CloseTime, model.MaxPlayers, model.description);
            return Redirect("index");
        }
        [Authorize(Roles = "2")]
        public ActionResult edit()
        {
            ContestModels model = new ContestModels();
            model.ContestID = Convert.ToInt16(Request.QueryString["cont"]);
            ContestModels.Contest con = new ContestModels.Contest();
            DataTable dt = con.GetContest(model.ContestID);
            foreach (DataRow dr in dt.Rows)
            {

                model.Name = (string)dr["Namn"];
                model.description = (string)dr["description"];
                model.MaxPlayers = (int)dr["Max spelare"];
                model.Timestart = (DateTime)dr["Start"];
                model.Timeend = (DateTime)dr["Slut"];
                model.CloseTime = (DateTime)dr["Sista anm."];
                model.ContestID = (int)dr["id"];
            }
          return View(model);
        }
        [HttpPost]
        public ActionResult edit(ContestModels model)
        {
            ContestModels.MakeCompetition edit = new ContestModels.MakeCompetition();
            edit.Editcontest(model.ContestID, model.Name, model.CloseTime, model.MaxPlayers, model.description,model.Publish);
            return Redirect("index");
        }
        public ActionResult delete()
        {
            ContestModels model = new ContestModels();
            model.ContestID = Convert.ToInt16(Request.QueryString["cont"]);
            ContestModels.Contest cont = new ContestModels.Contest();
            DataTable dt = cont.GetContest(model.ContestID);
            foreach (DataRow dr in dt.Rows)
            {
                model.Timestart = (DateTime)dr["Start"];
                model.Timeend = (DateTime)dr["Slut"];
                model.ContestID = (int)dr["id"];
            }
            ContestModels.MakeCompetition con = new ContestModels.MakeCompetition();
            con.DeleteContest(model.ContestID, model.Timestart, model.Timeend);
            return Redirect("index");
        }
        public ActionResult publish()
        {
            ContestModels model = new ContestModels();
            model.ContestID = Convert.ToInt16(Request.QueryString["cont"]);
            ContestModels.MakeCompetition con = new ContestModels.MakeCompetition();
            con.Publish(model.ContestID);
            return RedirectToAction("Admin", "contest", new { cont = model.ContestID });
        }
        [Authorize(Roles = "2")]
        [HttpPost]
        public ActionResult Admin(ContestModels model)
        {
            ContestModels.Contest runforestrun = new ContestModels.Contest();
            runforestrun.MembersInContestTimeSetting(model.ContestID);
            return RedirectToAction("Admin", "contest", new { cont = model.ContestID });
        }

        [Authorize(Roles = "2")]
        public ActionResult Admin()
        {
            ContestModels model = new ContestModels();
            model.ContestID = Convert.ToInt16(Request.QueryString["cont"]);
            ContestModels.Contest contests = new ContestModels.Contest();
            MemberModels members = new MemberModels();

            model.ContestMembers = contests.MembersInContest(model.ContestID);
            model.AllContests = members.CollectAllMembers();

            DataTable dt = contests.GetNameAndDate(model.ContestID);
            foreach (DataRow dr in dt.Rows)
            {
                model.Name = (string)dr["cn"];
                model.Timestart = (DateTime)dr["timestart"];
            }

            model.NameAndDate = model.Name + ": " + model.Timestart.ToShortDateString(); 
            return View(model);
        }

        //Get Member
        [HttpGet]
        public ActionResult Member()
        {
            ContestModels model = new ContestModels();
            model.ContestID = Convert.ToInt16(Request.QueryString["cont"]);
            ContestModels.Contest contests = new ContestModels.Contest();
            MemberModels members = new MemberModels();
            model.ContestMembers = contests.MembersInContest(model.ContestID);
            DataTable dt = contests.GetNameAndDate(model.ContestID);
            foreach (DataRow dr in dt.Rows)
            {
                model.Name = (string)dr["cn"];
                model.Timestart = (DateTime)dr["timestart"];
            }

            model.NameAndDate = model.Name + ": " + model.Timestart.ToShortDateString();

            return View(model);
        }

        [HttpPost]
        public ActionResult Member(ContestModels model)
        {
            ContestModels.Contest contests = new ContestModels.Contest();
            contests.AddPlayersToContest(model.ContestID, Convert.ToInt32(User.Identity.Name));
            return RedirectToAction("Member", "contest", new { cont = model.ContestID });
        }

        [Authorize(Roles = "2")]
        public ActionResult Addplayers()
        {
            ContestModels model = new ContestModels();
            model.ContestID = Convert.ToInt16(Request.QueryString["cont"]);
            int user_id = Convert.ToInt16(Request.QueryString["member"]);
            ContestModels.Contest contests = new ContestModels.Contest();
            contests.AddPlayersToContest(model.ContestID, user_id);
            return RedirectToAction("admin", "contest", new { cont = model.ContestID });
        }

        public ActionResult RemovePlayers()
        {
            ContestModels model = new ContestModels();
            model.ContestID = Convert.ToInt16(Request.QueryString["cont"]);
            int user_id = Convert.ToInt16(Request.QueryString["member"]);
            ContestModels.Contest contests = new ContestModels.Contest();
            contests.DeletePlayersFromContest(model.ContestID, user_id);
            return RedirectToAction("admin", "contest", new { cont = model.ContestID });
        }

        public ActionResult AddPlayersAsMember()
        {
            ContestModels model = new ContestModels();
            model.ContestID = Convert.ToInt16(Request.QueryString["cont"]);
            int user_id = Convert.ToInt16(User.Identity.Name);
            ContestModels.Contest contests = new ContestModels.Contest();
            contests.AddPlayersToContest(model.ContestID, user_id);
            return Redirect("admin");
        }

        public ActionResult Competition()
        {
            ContestModels.Contest contests = new ContestModels.Contest();
            ContestModels Model = new ContestModels();
            Model.AllContests = contests.GetAllContests();

            return View(Model);
        }
        public ActionResult deletemember()
        {
            ContestModels model = new ContestModels();
            model.ContestID = Convert.ToInt16(Request.QueryString["cont"]);
            ContestModels.Contest contests = new ContestModels.Contest();
            contests.DeletePlayersFromContest(model.ContestID, Convert.ToInt32(User.Identity.Name));
            return RedirectToAction("index", "Member");
        }
        public ActionResult CollectResult()
        {
            ContestScore model = new ContestScore();
            model.User_id = Convert.ToInt16(Request.QueryString["member"]);
            model.ContestID = Convert.ToInt16(Request.QueryString["cont"]);

            MemberModels member = new MemberModels();
            DataTable dt = member.CollectOneMember(model.User_id);
            foreach (DataRow dr in dt.Rows)
            {

                model.Name = (string)dr["firstname"];
                model.Name += " ";
                model.Name += (string)dr["lastname"];
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult CollectResult(ContestScore model)
        {
            int[] whacks = { model.Hole1, model.Hole2, model.Hole3, model.Hole4, model.Hole5, model.Hole6, model.Hole7,
                model.Hole8, model.Hole9, model.Hole10, model.Hole11, model.Hole12, model.Hole13, model.Hole14,
                model.Hole15, model.Hole16, model.Hole17, model.Hole18 };

            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Fyll i korrekt, Endast slag");
                // om inte rätt format
                return View(model);
            }
            ContestScore contest = new ContestScore();
            PostgresModels Database3 = new PostgresModels();

Golf4/Golf4/Controllers/MemberController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Golf4.Models;
using Microsoft.AspNet.Identity;
using System.Security.Claims;
using Npgsql;
using System.Data;

namespace Golf4.Controllers
{
    
    public class MemberController : Controller
    {
        // GET: Member
        public ActionResult Index()
        {
            // Bygg om metoderna och flyttat dessa till Models 
            MemberModels member = new MemberModels();
            MemberModels.MembersViewModel model = new MemberModels.MembersViewModel();
            ContestModels.Contest contests = new ContestModels.Contest();
            int user_id = Convert.ToInt16(User.Identity.Name);
            model.Timestart=member.GetBookingsOnMember(user_id);
            model.CompeteList = member.CollectContestWithMembers(user_id);
            model.MyContests = contests.MyFinishedContests(user_id);

            // Kommer starta med att bygga om den här under helgen
            PostgresModels sql = new PostgresModels();
            DataTable dt = sql.SqlQuery("SELECT members.id, members.firstname,members.lastname, members.address,members.postalcode,members.city,members.email,members.telephone,members.hcp,members.golfid,membercategories.category,genders.gender  FROM members LEFT JOIN membercategories ON members.membercategory = membercategories.id LEFT JOIN genders ON members.gender = genders.id where members.id = @par1", PostgresModels.list = new List<NpgsqlParameter>()
            {
                new NpgsqlParameter("@par1", user_id)
            });
            foreach (DataRow dr in dt.Rows)
            {
                model.ID =(int)dr["id"];
                model.Firstname = (string)dr["firstname"];
                model.Lastname = (string)dr["lastname"];
                model.Adress = (string)dr["address"];
                model.Postalcode = (string)dr["postalcode"];
                model.City = (string)dr["city"];
                model.Email = (string)dr["email"];
                model.Telephone = (string)dr["telephone"];
                model.GolfID = (string)dr["golfid"];
                model.HCP = (Double)dr["hcp"];
                model.Membercategory = (string)dr["category"];
                model.Gender = (string)dr["gender"];
            }

            TempData["user"] = model;



            return View(model);
        }


        // GET: Member/Edit/
        [HttpGet]
        public ActionResult Edit()
        {
          
            return View(TempData["user"]);
        }

        // POST: Member/Edit/5
        [HttpPost]
        public ActionResult Edit(FormCollection collection)
        {
            int id = Convert.ToInt16(User.Identity.Name);
            string fname = collection["Firstname"], lname = collection["lastname"], address = collection["adress"], postalcode = collection["postalcode"], city = collection["city"], email = collection["email"], telephone = collection["telephone"], hcp = collection["hcp"];
            double hcp1 = Convert.ToDouble(hcp);
            try
            {
                
                PostgresModels sql = new PostgresModels();
                sql.SqlNonQuery("UPDATE members SET firstname=@par2,lastname =@par3, address=@par4,postalcode=@par5,city=@par6,email=@par7,telephone=@par8,hcp=@par9 WHERE id =@par1", PostgresModels.list = new List<NpgsqlParameter>()
            {
                new NpgsqlParameter("@par2", fname),
                new NpgsqlParameter("@par3", lname),
                new NpgsqlParameter("@par4", address),
                new NpgsqlParameter("@par5", postalcode),
                new NpgsqlParameter("@par6", city),
                new NpgsqlParameter("@par7", email),
                new NpgsqlParameter("@par8", telephone),
                new NpgsqlParameter("@par9", hcp1),
                new NpgsqlParameter("@par1", id)
            });

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Member/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Member/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

    }
}

Golf4/Golf4/Views/Contest/Admin.cshtml
@using Golf4.Models
@using System.Data
@model ContestModels

@{
    ViewBag.Title = "Spelare i tävling";
}
<h2>@ViewBag.Title</h2>
<hr />

@using (Html.BeginForm())
{
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/pdfmake-0.1.18/dt-1.10.13/af-2.1.3/b-1.2.4/b-colvis-1.2.4/b-html5-1.2.4/b-print-1.2.4/fh-3.1.2/r-2.1.1/sc-1.4.2/se-1.2.0/datatables.min.css" />
    <script type="text/javascript" src="https://cdn.datatables.net/v/dt/pdfmake-0.1.18/dt-1.10.13/af-2.1.3/b-1.2.4/b-colvis-1.2.4/b-html5-1.2.4/b-print-1.2.4/fh-3.1.2/r-2.1.1/sc-1.4.2/se-1.2.0/datatables.min.js"></script>

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(Model => Model.ContestID)
        <div class="form-group">
            <div class="col-md-10">
                <h4>@Html.DisplayFor(model => Model.NameAndDate, new { htmlAttributes = new { @class = "form-control" } })</h4><br/>
            </div>
        </div>
        <table id="contest" class="dt-responsive no-wrap" style="width: 100%;">
            <thead>
                <tr>
                    @foreach (DataColumn item in Model.ContestMembers.Columns)
                {
                    <th> @item.ColumnName</th>
                }
                </tr>
            </thead>
            <tbody>
                @foreach (DataRow row in Model.ContestMembers.Rows)
                {
                <tr>

                    @foreach (DataColumn item in Model.ContestMembers.Columns)
                    {
                        
                        if (item.ColumnName == "Välj åtgärd")
                        {
                            <td>
                                @Html.ActionLink("Ta bort från tävling", "removeplayers", "contest", new { member = row[item.ColumnName], cont = Model.ContestID }, new { onclick = "return confirm('Vill du avanmäla denna tävling?');" }) <br />
                                @Html.ActionLink("Rapportera Resultat", "collectResult", "contest", new { member = row[item.ColumnName], cont = Model.ContestID }, null)
                                
                            </td>
                        }
                        else
                        {
                            <td>
                              @if (row[item.ColumnName].ToString() == "-1" )
                              {
                                 <p>n/a</p>
                              }
                              else
                              {
                                @row[item.ColumnName]
                              }
                              
                               
                                
                            </td>
                        }
                    }

                </tr>
                }
           
            </tbody>
        </table>
        <br />
        <input type="submit" class="btn btn-default" value="Slumpa starttider manuellt" style="background-color:darkred" onclick="return confirm('Är du säker på att du vill slumpa tiderna? Samtliga spelare i tävlingen kommer få information om ny tilldelad tid via e-post!') ? Model.MembersInContestTimeSetting(Model => Model.ContestID) : '';" /> <input type="button" class="btn btn-default memberbtn" value="Publicera resultat" style="background-color:darkred" onclick="window.location='@Url.Action("publish", new { cont = Model.ContestID})'"/>
        <br />
        <br />
            <table id="members" class="dt-responsive no-wrap" style="width: 100%;">
                <thead>
                    <tr>
                        @foreach (DataColumn item in Model.AllContests.Columns)
                        {
                            <th> @item.ColumnName</th>
                        }
                    </tr>
                </thead>
                <tbody>
                    @foreach (DataRow row in Model.AllContests.Rows)
                {
                        <tr>
                            @foreach (DataColumn item in Model.AllContests.Columns)
                            {
                                <td>
                                    @{if (item.ColumnName == "id")
                                        {
                                            @Html.ActionLink("Lägg till i tävling", "addplayers", "contest", new { member = row[item.ColumnName], cont = Model.ContestID }, null)<br />

                                        }
                                        else
                                        {
                                            @row[item.ColumnName]
                                        }
                                    }
                                </td>
                                        }
                        </tr>
                                        }
                </tbody>
            </table>
            <a class="btn btn-default btnadmin" href="~/contest/index">Tillbaka</a>
            <script>
                $(document).ready(function () {
                    $('#members').DataTable({
                        language: {
                            url: '//cdn.datatables.net/plug-ins/1.10.12/i18n/Swedish.json'
                        },
                        responsive: true
                    });
                });

                $(document).ready(function () {
                    $('#contest').DataTable({
                        language: {
                            url: '//cdn.datatables.net/plug-ins/1.10.12/i18n/Swedish.json'
                        },
                        responsive: true,
                        fixedHeader: true,
                        dom: 'Blfrtip',
                        buttons: [{
                            extend: 'collection',
                            text: 'Exportera',
                            buttons: [
                                { extend: 'copy', text: 'Kopiera' },
                                { extend: 'excel', text: 'Excel' },
                                { extend: 'pdf', text: 'PDF' },
                                { extend: 'print', text: 'Skriv ut' }
                            ],
                        }],
                    })
                });

            </script>
        </div>
                                    }

Golf4/Golf4/Views/Contest/Contests.cshtml
@model Golf4.Models.ContestModels
@using System.Data

@{
    ViewBag.Title = "Tävlingar";
}

<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/pdfmake-0.1.18/dt-1.10.13/af-2.1.3/b-1.2.4/b-colvis-1.2.4/b-html5-1.2.4/b-print-1.2.4/fh-3.1.2/r-2.1.1/sc-1.4.2/se-1.2.0/datatables.min.css" />
<script type="text/javascript" src="https://cdn.datatables.net/v/dt/pdfmake-0.1.18/dt-1.10.13/af-2.1.3/b-1.2.4/b-colvis-1.2.4/b-html5-1.2.4/b-print-1.2.4/fh-3.1.2/r-2.1.1/sc-1.4.2/se-1.2.0/datatables.min.js"></script>

<h2>Tävlingar</h2>

<h5>Markera en tävling för att visa mer information</h5>

<table id="contest" class="dt-responsive no-wrap" style="width: 100%;">
    <thead>
        <tr>
            @foreach (DataColumn item in Model.AllContests.Columns)
            {
                <th> @item.ColumnName</th>
            }
        </tr>
    </thead>
    <tbody>
        @foreach (DataRow row in Model.AllContests.Rows)
        {
            <tr>

                @foreach (DataColumn item in Model.AllContests.Columns)
                {
                        <td>
                            @row[item.ColumnName]
                        </td>
                }

            </tr>
        }

    </tbody>
</table>
<br />
<div id="events">
</div>
<a class="btn btn-default" href="~/Home/Contests">Tillbaka</a>

<script>
            $(document).ready(function () {
                var events = $('#events');
                var table = $('#contest').DataTable({
                    select: true,
                    "info": false,
                    language: {
                        url: '//cdn.datatables.net/plug-ins/1.10.12/i18n/Swedish.json'
                    }
                });
                table.column(6).visible(false);
                table.column(5).visible(false);
                table
                    .on('select', function (e, dt, type, indexes) {
                        var contestname = table.rows(indexes).column(0).data().toArray();
                        var descr = table.rows(indexes).column(6).data().toArray();
                        events.prepend('<div id="descr">' + descr + '</div>');
                        events.prepend('<div id="contestname"> <h2>' + contestname + '</h2></div>');
                    })

                    .on('deselect', function (e, dt, type, indexes) {
                        $('#contestname').remove();
                        $('#descr').remove();
                    });
    });
</script>

Golf4/Golf4/Views/Contest/Index.cshtml
@using Golf4.Models
@using System.Data
@model ContestModels
@{
    ViewBag.Title = "Tävlingar";
}
<h2>@ViewBag.Title</h2>
<hr />

<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/pdfmake-0.1.18/dt-1.10.13/af-2.1.3/b-1.2.4/b-colvis-1.2.4/b-html5-1.2.4/b-print-1.2.4/fh-3.1.2/r-2.1.1/sc-1.4.2/se-1.2.0/datatables.min.css" />
<script type="text/javascript" src="https://cdn.datatables.net/v/dt/pdfmake-0.1.18/dt-1.10.13/af-2.1.3/b-1.2.4/b-colvis-1.2.4/b-html5-1.2.4/b-print-1.2.4/fh-3.1.2/r-2.1.1/sc-1.4.2/se-1.2.0/datatables.min.js"></script>

@if (User.IsInRole("2"))
{
    <a class="btn btn-default" href="~/Contest/create">Skapa ny tävling</a>
    <br />
    <hr />
}

<div>
    <h3>Kommande tävlingar</h3><br/>
    <table id="contests" class="dt-responsive no-wrap" style="width: 100%;">
        <thead>
            <tr>
                @foreach (DataColumn item in Model.AllContests.Columns)
                {
                    <th> @item.ColumnName</th>
                }

            </tr>
        </thead>
        <tbody>
            @foreach (DataRow row in Model.AllContests.Rows)
            {
                <tr>
                    @foreach (DataColumn item in Model.AllContests.Columns)
                    {
                        <td>
                            @if (item.ColumnName == "id")
                            {
                                if (User.IsInRole("2"))
                                {
                                    @Html.ActionLink("Hantera medlemmar", "Admin", "Contest", new { cont = row[item.ColumnName] }, null) <br />
                                    @Html.ActionLink("Ändra tävlingsinfo", "edit", "Contest", new { cont = row[item.ColumnName] }, null)  <br />
                                    @Html.ActionLink("Ta bort tävling", "delete", "Contest", new { cont = row[item.ColumnName] }, new { onclick = "return confirm('Vill du ta bort denna tävling?');" })
                                }
                                else
                                {
                                    @Html.ActionLink("Boka", "Member", "Contest", new { cont = row[item.ColumnName] }, null)
                                }
                            }
                            else
                            {
                                @row[item.ColumnName];
                            }

                        </td>
                    }
                </tr>
            }
        </tbody>
    </table>
    <hr />
</div>
<div>
     <h3>Avslutade tävlingar</h3><br />
    <table id="publishedcontests" class="dt-responsive no-wrap" style="width: 100%;">
        <thead>
            <tr>
                @foreach (DataColumn item in Model.PublishedContests.Columns)
                {
                    <th> @item.ColumnName</th>
                }

            </tr>
        </thead>
        <tbody>
            @foreach (DataRow row in Model.PublishedContests.Rows)
            {
                <tr>
                    @foreach (DataColumn item in Model.PublishedContests.Columns)
                    {
                        <td>
                            @if (item.ColumnName == "id")
                            {
                                @Html.ActionLink("Visa resultat", "ResultList", "Contest", new { cont = row[item.ColumnName] }, null)
                               
                            }
                            else
                            {
                                @row[item.ColumnName];
                            }

                        </td>
                    }
                </tr>
            }
        </tbody>
    </table>


    <script>
    $(document).ready(function () {
                $('#contests').DataTable({
                    language: {
                        url: '//cdn.datatables.net/plug-ins/1.10.12/i18n/Swedish.json'
                    },
                    responsive: true
                })
            }
        );


    $(document).ready(function () {
        $('#publishedcontests').DataTable({
            language: {
                url: '//cdn.datatables.net/plug-ins/1.10.12/i18n/Swedish.json'
            },
            responsive: true
        })
    }
    );

    </script>
</div>